
echo "Running 80/20 multifractal generation code"
#add a call to your code here, e.g. python mfractal.py

echo "Plotting the histogram of the 80/20 data"
#plot the histogram of the data generated by the previous step

echo "Running 70/20/10 multifractal generation code"
#add a call to your code here, e.g. python mfractal3.py

echo "Plotting the histogram of the 70/20/10 data"
#plot the histogram of the data generated by the previous step

echo "Running FDNQ on the 80/20 multifractal "
#add a call to the FDNQ code here

echo "Plotting the correlation integral of the 80/20, using FDNQ"
#call to your code here

echo "Running FDNQ on the 70/20/10 multifractal "
#add a call to the FDNQ code here

echo "Plotting the correlation integral of the 70/20/10, using FDNQ"
#call to your code here

echo "Computing the exact correlation integral for the 80/20 multifractal "
#call to your code here

echo "Plotting the exact correlation integral of the 80/20"
#call to your code here

echo "Computing the exact correlation integral for the 70/20/10 multifractal "
#call to your code here

echo "Plotting the exact correlation integral of the 70/20/10"
#call to your code here